version: 2.1
executors:
  android-executor:
    docker:
      - image: cimg/android:2024.01.1
    working_directory: ~/project
jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Set up Java 17 and 20
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
      - run:
          name: Make gradlew executable
          command: chmod +x gradlew
      - run:
          name: Build with Gradle
          command: ./gradlew build
      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
          name: Build Project (Assemble APK)
          command: ./gradlew assemble
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
